<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$helperData = $block->getHelperData();
$isCaptchaEnabled = $helperData->getIsEnabled();
$isCheckBoxType = $helperData->getIsCheckBox();
$isInvisibleType = $helperData->getIsInvisible();
$publicSiteKey = $helperData->getPublicSiteKey();

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<div class="block block-customer-login">
    <div class="block-title">
        <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Registered Customers')) ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
                <div class="field note"><?= $block->escapeHtml(__('If you have an account, sign in with your email address.')) ?></div>
                <div class="field email required">
                    <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                    <div class="control">
                        <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required">
                    <label for="pass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                    <div class="control">
                        <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
                    </div>
                </div>


                <?php if ($isCaptchaEnabled) :?>
                    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
                    <?php if ($isCheckBoxType) :?>
                        <div class="field google-captcha required">
                            <div class="control">
                                <div class="g-recaptcha" data-sitekey="<?= $publicSiteKey; ?>"></div>
                            </div>
                        </div>
                    <?php endif;?>
                <?php endif;?>

                <?= $block->getChildHtml('form_additional_info') ?>
                <div class="actions-toolbar">
                    <?php if ($isCaptchaEnabled && $isInvisibleType) :?>
                        <script>
                            function onSubmit(token) {
                                document.getElementById("login-form").submit();
                            }
                        </script>
                        <div class="primary"><button type="submit" class="action login primary g-recaptcha" data-sitekey="<?= $publicSiteKey; ?>" data-callback="onSubmit" name="send" id="send2"><span><?= $block->escapeHtml(__('Sign In')) ?></span></button></div>
                    <?php else :?>
                        <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span><?= $block->escapeHtml(__('Sign In')) ?></span></button></div>
                    <?php endif;?>
                    <div class="secondary"><a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a></div>
                </div>
            </fieldset>
        </form>
    </div>
</div>

